[[headers]]
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "GET, POST, OPTIONS"
  Access-Control-Allow-Headers = "Content-Type"

# Pagefind assets
[[redirects]]
from = "/e-klaim-doc/pagefind/*"
to = "https://inacbg.kemkes.go.id/e-klaim-doc/pagefind/:splat"
status = 200

# Static assets
[[redirects]]
from = "/e-klaim-doc/assets/*"
to = "https://inacbg.kemkes.go.id/e-klaim-doc/assets/:splat"
status = 200

# wasm
[[redirects]]
from = "/e-klaim-doc/*.wasm"
to = "https://inacbg.kemkes.go.id/e-klaim-doc/:splat"
status = 200

# fallback (VERY IMPORTANT)
[[redirects]]
from = "/pagefind/*"
to = "https://inacbg.kemkes.go.id/e-klaim-doc/pagefind/:splat"
status = 200
force = true