[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# rewrite pagefind root
[[redirects]]
from = "/pagefind/*"
to = "https://inacbg.kemkes.go.id/e-klaim-doc/pagefind/:splat"
status = 200
force = true

# rewrite assets
[[redirects]]
from = "/assets/*"
to = "https://inacbg.kemkes.go.id/e-klaim-doc/assets/:splat"
status = 200
force = true

# rewrite main docs
[[redirects]]
from = "/*"
to = "https://inacbg.kemkes.go.id/e-klaim-doc/:splat"
status = 200
force = true